import {StyleSheet,Dimensions} from 'react-native';
const estilos=StyleSheet.create({
    container:{
        width:'100%',
        padding:20
    },
    title:{
        fontSize:20,
        color:'red'
    },
    text:{
        fontSize:16,
        color:'#6f6f6f'
    },
    textinput:{
        borderColor:'#6f6f6f',
        borderWidth:1,
        borderRadius:15,
        width:'90%'
    },
    inputcontainer:{
        marginTop:20,
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        rowGap:10
    },
    boton:{
        backgroundColor:'#5897fb',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:15,
        width:'25%',
        height:'auto',
        paddingTop:10,
        paddingBottom:10
    },
    itemcontainer:{
        paddingVertical:20,
        borderBottomColor:'#6f6f6f',
        borderBottomWidth:1,
        flexDirection:'row',
        justifyContent:'space-between'
    },
    textDone:{
        fontSize:16,
        color:'#6f6f6f',
        textDecorationLine:'line-through'
    },
    removeBoton:{
        backgroundColor:'red',
        justifyContent:'center',
        alignItems:'center',
        paddingHorizontal:15,
        borderRadius:10
    },
    ContenedorBoton:{
        display:'flex',
        flexDirection:'row',
        gap:25
    }
})
export default estilos